### ISSUE TITLE
no module named emailutil

### ISSUE THREAD

**Issue by buster** [OfflineIMAP/offlineimap#187]
From the "next" branch:

```
[buster@Fry➔ ~/sources/offlineimap] ./offlineimap.py --help
Traceback (most recent call last):
  File "./offlineimap.py", line 33, in <module>
    from offlineimap import OfflineImap
  File "/home/buster/sources/offlineimap/offlineimap/__init__.py", line 21, in <module>
    from offlineimap.init import OfflineImap
  File "/home/buster/sources/offlineimap/offlineimap/init.py", line 28, in <module>
    from offlineimap import accounts, threadutil, syncmaster
  File "/home/buster/sources/offlineimap/offlineimap/accounts.py", line 25, in <module>
    from offlineimap.repository import Repository
  File "/home/buster/sources/offlineimap/offlineimap/repository/__init__.py", line 25, in <module>
    from offlineimap.repository.IMAP import IMAPRepository, MappedIMAPRepository
  File "/home/buster/sources/offlineimap/offlineimap/repository/IMAP.py", line 25, in <module>
    from offlineimap import folder, imaputil, imapserver, OfflineImapError
  File "/home/buster/sources/offlineimap/offlineimap/folder/__init__.py", line 1, in <module>
    from . import Base, Gmail, IMAP, Maildir, LocalStatus
  File "/home/buster/sources/offlineimap/offlineimap/folder/Maildir.py", line 22, in <module>
    import emailutil
ImportError: No module named emailutil
```

**Comment by nicolas33** [comment]
Hi buster,

I should have fixed this yesterday. ,-)
Could you please update and confirm?

**Comment by buster** [comment]
Yes, i think it is not working since the latest commit.
I can run ./offlineimap.py with the commit 05d6357adce228817a41c733ce4a7f00264ce17f but it breaks when using 71693b7d8c6cd51219e811eee7bb03af341ae544.

Do i need to clean/remove some files, maybe?

**Comment by nicolas33** [comment]
Oh, sorry, I did a mistake in the fix. Fixed now.

**Comment by nicolas33** [comment]
Do you run the `next` branch in a regular basis?

**Comment by buster** [comment]
Hi, thanks!
Yes, i do, because the master had some problems not fixed...
