### ISSUE TITLE
offlineimap confused after (suspend and) resume

### ISSUE THREAD

**Issue by quite** [OfflineIMAP/offlineimap#56]
I have at (almost) all times offlineimap running in a tmux. After resuming my compu, offlineimap has problems to reconnect properly. 
Often it just hangs for a long time (or indefinetely) while nothing seems to happen.

I came up with a  solution to the problem by having a resume-script that sends SIGUSR2 to my running offlineimap, whereafter it is automatically restarted.

The problem though, is that sometimes offlineimap takes a long time to exit upon SIGUSR2. Maybe this is again related to the lost tcp connections, timeouts, and such. And essentially the same problem as above.

Any suggestions on how I should solve? I have been reluctant to just send SIGKILL to the process, because I was afraid that this might cause inconsistencies in the repo, or such. But maybe this is what I need and should to do?

**Comment by nicolas33** [comment]
Requires to be documented in `known issues`.

**Comment by nicolas33** [comment]
Done in cd962d4.

**Comment by doy** [comment]
As I mentioned, setting `socktimeout` doesn't actually fix the problem - it makes it less frequent, but it still happens to me all the time even with this set. I don't think this is a sufficient fix.

**Comment by nicolas33** [comment]
Ok. I know current behaviour sucks. Sadly, it's hard to handle this properly so don't expect this to be fixed soon.

**Comment by ezyang** [comment]
There are two things I would suggest here:

1. If the first C-c attempts a graceful exit, the second C-c should hard exit. 
2. I'm pretty sure the remaining hanging is from the timeout not being applied to all blocking calls. This is something an audit should be able to catch.

**Comment by nicolas33** [comment]
Hi Edward,
1. Yes, I've already suggested to handle the second Ctrl-c as hard exit.
2. On resume the timeout might require to wait until the local time is adjusted. Or wait until the timeout is hit. BTW, the broken socket should be better handled.
I'm planning a deep refactoring and such issues should be made easier to fix. You might be interested in following the coming changes.

**Comment by dolohow** [comment]
Still happening on 6.6.1

**Comment by nicolas33** [comment]
Fix to force OfflineIMAP to stop with consecutives `ctrl+c` was merged some days ago. Will be in the next release (6.7.0-rc2).
AFAIK, nobody worked on proper resume at wakeup.

**Comment by dolohow** [comment]
Thank you for the update.  If someone could tell me what should be done,
maybe I would try to iplement that feature.

**Comment by toogy** [comment]
I'm also interested in someone fixing this. I have the same issue. :sweat_smile:

**Comment by nicolas33** [comment]
- Naive but still effective approach would be to introduce print statements to find a blocker.
- A more advanced way can be to try `strace` while this can be tricky to map the output to lines of code.
- Python includes debugging tools that could be usefull. Most appealing for the purpose might worth a try.
- Team working can greatly help. Do share your analysis, success and failures.

Bear in mind there might be more than one blocker.

**Comment by pwnage101** [comment]
Assuming this will be difficult to debug, can we at least implement a SIG{INT,TERM} handler which deletes the lockfile?  I currently have to delete `.offlineimap/*.lock` files every time I resume from suspend because when offlineimap freezes it leaves the lockfiles hanging around.

**Comment by nicolas33** [comment]
> Assuming this will be difficult to debug, can we at least implement a SIG{INT,TERM} handler which deletes the lockfile? I currently have to delete .offlineimap/*.lock files every time I resume from suspend because when offlineimap freezes it leaves the lockfiles hanging around.

Please, try v6.7.0 or later.

**Comment by pwnage101** [comment]
Ah, since I run offlineimap as a notmuch hook, when I hit CTRL-C offlineimap was getting reparented to init, returning me to the shell but without actually killing the sync threads.  If i wait another couple of seconds after CTRL-C, the lockfiles disappear and I can re-run notmuch.

By the way, I am running v6.7.0, but I was wrongly blaming offlineimap for something that seems to be an issue with notmuch or my configuration.

**Comment by nicolas33** [comment]
@pwnage101 You might like to try SIGQUIT. Unix signals handling is explained [in the manual](https://github.com/OfflineIMAP/offlineimap/blob/master/docs/offlineimap.txt#L308).

**Comment by sim590** [comment]
While the popular reaction to this problem seems to be to restart `offlineimap`, I might point out that restarting offlineimap might not be ideal. For instance, if you have your passwords being retrieved by a subprocess using `gpg-agent`, each time the connectivity issue occurs, `gpg-agent` will ask for your password which can appear weird at first while you're not aware this is related to offlineimap restarting in the background and also annoying if it happens alot. Therefor, I'm really looking forward to a solution.

**Comment by pwnage101** [comment]
I said earlier:

> If i wait another couple of seconds after CTRL-C, the lockfiles disappear and I can re-run notmuch.

I should clarify that sometimes if i resume from suspend, offlineimap _will_ hang forever.
